name: Call API Example

on: push
#on:
#  workflow_dispatch:
#    inputs:
#      partition:
#        required: true
#        type: choice
#        default: 'aaa'
#        options:
#        - aaa
#        - bbb
#
#      G:
#        required: true
#        type: string
#        default: 'warning'
#      N:
#        required: true
#        type: string
#        default: 'warning'

jobs:
  run_tests:
    runs-on:
      - self-hosted
    steps:
    - name: Run script file
      run: |
         pwd
         chmod +x script/test.sh
         /root/WORK/gitTest/test-jos/test1/.github/script/test.sh
      shell: bash

