name: Call API Example

on:
  workflow_dispatch:
    inputs:
      partition:
        required: true
        type: choice
        default: 'aaa'
        options:
        - aaa
        - bbb

      G:
        required: true
        type: string
        default: 'warning'
      N:
        required: true
        type: string
        default: 'warning'

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./public/scripts/test.sh
         ./public/scripts/test.sh
      shell: bash

