name: Call API Example

on: push
env:
  a: [jos, josef ]
  b: yoss

#on:
#  workflow_dispatch:
#    inputs:
#      partition:
#        required: true
#        type: choice
#        default: 'aaa'
#        options:
#        - aaa
#        - bbb
#
#      G:
#        required: true
#        type: string
#        default: 'warning'
#      N:
#        required: true
#        type: string
#        default: 'warning'

jobs:
  strategy:
    matrix:
      version: [jos, josef, JOSEF]
  run_tests:
    runs-on:
      - self-hosted
    steps:
    - name: Run script file
      run: |
         pwd
         /home/jos/test.sh ${{ matrix.version }}
      shell: bash

