name: Sample Matrix Parallel
on: push
jobs:
  job:
    runs-on:  self-hosted
    strategy:
      max-parallel: 2
      matrix: 
        run: ['run1', 'run2']
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
    - name: Run script file
      run: |
         pwd
         /home/jos/test.sh ${{ matrix.run }}
      shell: bash

